# =============================================================
# STATEFULSET DEMO — Persistent Storage on Karpenter Nodes
# =============================================================
# This demo shows:
#   1. StatefulSet with PVC (persistent storage per pod)
#   2. Each pod gets its own EBS volume (unique identity)
#   3. Data survives pod restarts (prove with kubectl exec)
#   4. Karpenter provisions nodes with EBS CSI Driver
#
# KEY DIFFERENCE from Deployment:
#   Deployment:   pods are stateless, interchangeable
#   StatefulSet:  pods have stable identity (web-0, web-1, web-2)
#                 + each pod has its OWN persistent volume
#
# HOW TO RUN:
#   kubectl apply -f examples/statefulset-demo.yaml
#
# VERIFY PERSISTENCE:
#   # Write data to pod-0
#   kubectl exec -n karpenter-demo stateful-app-0 -- sh -c "echo 'Hello from pod-0' > /data/test.txt"
#   kubectl exec -n karpenter-demo stateful-app-0 -- cat /data/test.txt
#
#   # Delete the pod (StatefulSet recreates it)
#   kubectl delete pod -n karpenter-demo stateful-app-0
#
#   # Wait for pod to restart, data should still be there!
#   kubectl exec -n karpenter-demo stateful-app-0 -- cat /data/test.txt
# =============================================================

---
# -------------------------------------------------------
# StorageClass — Uses EBS CSI Driver (gp3, faster + cheaper)
# -------------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer   # Only create EBS when pod is scheduled
reclaimPolicy: Delete                     # Delete EBS when PVC is deleted
parameters:
  type: gp3
  encrypted: "true"                       # Always encrypt at rest
  fsType: ext4

---
# -------------------------------------------------------
# StatefulSet — 3 pods, each with its own PVC/EBS volume
# -------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-app
  namespace: karpenter-demo
  labels:
    app: stateful-app
    demo: statefulset
spec:
  serviceName: stateful-app   # Required for StatefulSet stable DNS
  replicas: 3                 # Creates: stateful-app-0, stateful-app-1, stateful-app-2
  selector:
    matchLabels:
      app: stateful-app
  template:
    metadata:
      labels:
        app: stateful-app
    spec:
      # Let Karpenter decide the best node (any architecture)
      tolerations:
        - key: karpenter.sh/capacity-type
          operator: Exists
      containers:
      - name: app
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Write pod identity to persistent volume on startup
            echo "Pod $(hostname) started at $(date)" >> /data/log.txt
            echo "Node: $NODE_NAME" >> /data/log.txt
            # Keep container running
            while true; do sleep 30; done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: data          # Each pod gets its OWN volume
          mountPath: /data

  # VolumeClaimTemplate — creates 1 PVC per pod automatically
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]   # One pod at a time (EBS limitation)
      storageClassName: ebs-gp3
      resources:
        requests:
          storage: 1Gi                 # 1 GB EBS per pod

---
# -------------------------------------------------------
# Headless Service — required for StatefulSet DNS
# Gives each pod a stable DNS: stateful-app-0.stateful-app.karpenter-demo.svc.cluster.local
# -------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: stateful-app
  namespace: karpenter-demo
  labels:
    app: stateful-app
spec:
  clusterIP: None    # Headless — no single IP, direct pod DNS
  selector:
    app: stateful-app
  ports:
  - port: 80
    name: web
